{% set version = "0.3.0.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-secretbase
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/secretbase_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/secretbase/secretbase_{{ version }}.tar.gz
  sha256: 3c9457248ea13f457200e381f8ea3ef72d29dc09a0524afea320bc32e89c0e56

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'  # [win]

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('secretbase')"           # [not win]
    - "\"%R%\" -e \"library('secretbase')\""  # [win]

about:
  home: https://shikokuchuo.net/secretbase/
  dev_url: https://github.com/shikokuchuo/secretbase/
  license: GPL-3.0-or-later
  summary: SHA-3 cryptographic hash and SHAKE256 extendable-output functions (XOF). The SHA-3 Secure Hash Standard was published by the National Institute of Standards and Technology (NIST) in 2015 at <doi:10.6028/NIST.FIPS.202>. Fast and memory-efficient implementation using the core algorithm from 'Mbed TLS' under the
    Trusted Firmware Project <https://www.trustedfirmware.org/projects/mbed-tls/>.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - brendanf

# Package: secretbase
# Type: Package
# Title: Cryptographic Hash and Extendable-Output Functions
# Version: 0.2.0
# Description: SHA-3 cryptographic hash and SHAKE256 extendable-output functions (XOF). The SHA-3 Secure Hash Standard was published by the National Institute of Standards and Technology (NIST) in 2015 at <doi:10.6028/NIST.FIPS.202>. Fast and memory-efficient implementation using the core algorithm from 'Mbed TLS' under the Trusted Firmware Project <https://www.trustedfirmware.org/projects/mbed-tls/>.
# Authors@R: c(person(given = "Charlie", family = "Gao", role = c("aut", "cre"), email = "charlie.gao@shikokuchuo.net", comment = c(ORCID = "0000-0002-0750-061X")), person(given = "Hibiki AI Limited", role = "cph"))
# License: GPL (>= 3)
# BugReports: https://github.com/shikokuchuo/secretbase/issues
# URL: https://shikokuchuo.net/secretbase/, https://github.com/shikokuchuo/secretbase/
# Encoding: UTF-8
# Depends: R (>= 3.5)
# RoxygenNote: 7.3.1
# NeedsCompilation: yes
# Packaged: 2024-02-01 09:26:19 UTC; cg334
# Author: Charlie Gao [aut, cre] (<https://orcid.org/0000-0002-0750-061X>), Hibiki AI Limited [cph]
# Maintainer: Charlie Gao <charlie.gao@shikokuchuo.net>
# Repository: CRAN
# Date/Publication: 2024-02-01 09:40:02 UTC
